In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('datashare.csv')
df['DATE']=pd.to_datetime(df['DATE'],format='%Y%m%d')

In [3]:
df.head(10)

,permno,DATE,mvel1,beta,betasq,chmom,dolvol,idiovol,indmom,mom1m,...,stdcf,ms,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,sic2
0,10006,1957-01-31,82249.000,1.122846,1.260784,0.047180,9.569953,0.025742,0.046433,0.044843,...,NaN,NaN,0.013234,9.411565e-08,0.015453,0.008058,0.355638,0.460420,1.120996e-07,37.0
1,10014,1957-01-31,3903.375,0.426734,0.182102,-0.275641,6.237836,0.072103,0.046433,-0.086957,...,NaN,NaN,0.033305,6.610609e-06,0.047619,0.033495,1.152126,1.169610,9.229146e-08,NaN
2,10022,1957-01-31,9273.250,1.066449,1.137313,-0.025490,7.008844,0.027648,0.046433,-0.060377,...,NaN,NaN,0.016023,2.286832e-06,0.020833,0.015589,0.815777,0.679803,1.181757e-07,NaN
3,10030,1957-01-31,54465.875,0.926038,0.857547,0.018171,9.825337,0.021700,0.046433,0.044633,...,NaN,NaN,0.015295,1.464273e-07,0.039326,0.015849,0.739302,1.333656,6.126699e-08,NaN
4,10057,1957-01-31,40250.000,1.247748,1.556875,0.025785,7.901007,0.025506,0.046433,0.086667,...,NaN,NaN,0.005954,1.380375e-06,0.056856,0.019945,0.755510,0.410391,3.315790e+00,NaN
5,10065,1957-01-31,76945.250,1.264106,1.597964,0.193374,8.906529,0.023942,0.046433,0.077778,...,NaN,NaN,0.008934,1.393915e-07,0.022222,0.008179,0.561265,0.461107,1.687356e-07,NaN
6,10102,1957-01-31,186193.500,1.445027,2.088104,-0.058910,10.375318,0.025526,0.046433,0.041237,...,NaN,NaN,0.009637,7.398559e-08,0.017632,0.008298,0.787710,0.773360,1.530290e-07,28.0
7,10137,1957-01-31,225984.000,0.585546,0.342864,-0.090805,8.887653,0.018691,0.046433,0.018779,...,NaN,NaN,0.013150,1.679162e-07,0.023923,0.009137,0.597666,0.106998,6.616541e-07,49.0
8,10145,1957-01-31,962994.375,1.132210,1.281900,-0.084218,10.850652,0.023319,0.046433,0.052846,...,NaN,NaN,0.016536,2.909367e-08,0.024324,0.013477,0.410964,0.174574,2.830609e-07,99.0
9,10153,1957-01-31,279846.875,1.173314,1.376666,-0.008426,10.547950,0.021665,0.046433,0.117886,...,NaN,NaN,0.016482,3.379634e-08,0.027132,0.011101,0.452489,0.527789,1.000562e-07,13.0

In [159]:
# check some slices
#firm_11618 = df.loc[(slice(None), 11618), :]
firm_92547 = df[df['permno']==87039]
#firm_10585.to_csv('firm_10585.csv')
firm_92547.iloc[155:165]

#firm_10051 = df[df['permno']==10051]

,permno,DATE,mvel1,beta,betasq,chmom,dolvol,idiovol,indmom,mom1m,...,ms,baspread,ill,maxret,retvol,std_dolvol,std_turn,zerotrade,sic2,date_cat
2296193,87039,1998-06-30,84508.5,0.476864,0.227399,-0.565062,10.481224,0.051858,0.346856,-0.036364,...,NaN,0.032954,9.561516e-07,0.037037,0.017532,1.464317,0.970209,12.600000,67.0,497
2305205,87039,1998-07-31,81319.5,0.585786,0.343145,-0.585714,8.617084,0.051137,0.225475,-0.037736,...,NaN,0.065528,2.555982e-06,0.052288,0.021496,1.166591,0.306550,13.363637,67.0,498
2314206,87039,1998-08-31,87166.0,0.613555,0.376449,-0.689188,7.614435,0.051196,0.133959,0.071895,...,NaN,0.033458,1.208878e-06,0.053082,0.031441,1.375626,1.583678,6.681818,67.0,499
2323161,87039,1998-09-30,68032.0,0.554746,0.307743,-0.676329,9.749053,0.051176,0.060948,-0.219512,...,NaN,0.037231,1.390769e-06,0.158813,0.050457,1.446147,2.367480,6.000000,67.0,500
2332036,87039,1998-10-30,73347.0,0.715672,0.512187,-0.612474,9.875911,0.049205,-0.119778,0.078125,...,NaN,0.067871,4.405367e-06,0.125000,0.042051,1.349685,1.658112,4.000000,67.0,501
2340816,87039,1998-11-30,68032.0,0.766109,0.586923,-0.856788,9.093919,0.048597,-0.032676,-0.051594,...,NaN,0.061463,3.234001e-06,0.060484,0.035698,1.227383,0.353117,6.681819,60.0,502
2349559,87039,1998-12-31,69095.0,0.663349,0.440032,-0.590003,8.210668,0.047021,-0.062913,0.015625,...,NaN,0.058833,1.066020e-05,0.281250,0.095850,1.418542,0.503614,11.550000,60.0,503
2358239,87039,1999-01-29,74410.0,0.636111,0.404638,-0.278665,8.163371,0.047163,-0.021816,0.076923,...,NaN,0.040623,1.891803e-06,0.111111,0.040865,0.971663,0.455376,7.636364,60.0,504
2366878,87039,1999-02-26,65906.0,0.592727,0.351325,-0.346344,8.807621,0.046866,-0.018362,-0.114286,...,NaN,0.061771,3.884947e-06,0.160714,0.057756,1.026726,0.641374,6.631579,60.0,505
2375483,87039,1999-03-31,75473.0,0.653388,0.426915,0.245447,8.648923,0.047952,-0.044001,0.145161,...,NaN,0.050655,2.547997e-06,0.064516,0.028198,1.351475,0.336991,12.157896,60.0,506

In [ ]:
# check sic unique dummies

In [82]:
permno_unique = np.sort(df['permno'].unique())
sic2 = pd.DataFrame(None, index=permno_unique, columns=['sic_2_1','sic_2_2','date_cat_'])
for v in range(len(permno_unique)):
    slicer = df[df['permno']==permno_unique[v]]
    unique_sic = slicer['sic2'].dropna().unique()
    if unique_sic.size > 0:
        sic2.loc[permno_unique[v]]['sic_2_1'] = unique_sic[0]
        if unique_sic.size > 1:
            sic2.loc[permno_unique[v]]['sic_2_2'] = unique_sic[1]

In [83]:
sic2.to_csv('permno_sic2.csv')

In [150]:
slicer = df[df['permno']==10051]
unique_sic = slicer['sic2'].dropna().unique()

In [137]:
sb_sic = double_sic2.index
sic_doubles = pd.DataFrame(None, index=sb_sic, columns=['sic_2_1_dc','sic_2_2_dc'])

In [143]:
for vv in sb_sic:
    sic11 = sic2.loc[vv]['sic_2_1']
    sic22 = sic2.loc[vv]['sic_2_2']
    slicer = df[df['permno']==vv]
    sic_doubles.loc[vv]['sic_2_1_dc'] = min(slicer[slicer['sic2']==sic11]['date_cat'])
    sic_doubles.loc[vv]['sic_2_2_dc'] = min(slicer[slicer['sic2']==sic22]['date_cat'])

In [ ]:
pd.concat([sic2, sic_doubles],axis=1).to_csv('permno_sic2_dc.csv')

In [104]:
# Add own index: 0 - 780
cat_list=[]
for i in range(780):
    cat_list.append(i)
df_cat=pd.concat([pd.Series(df['DATE'].unique()).rename('DATE'),pd.Series(cat_list).rename('date_cat')],axis=1)
df=df.merge(df_cat,on=['DATE'])

In [ ]:
# load CRSP monthly returns
price=pd.read_csv('crsp_price.csv',parse_dates=True)
price=price.iloc[:,1:]
price.rename(columns={'date':'DATE'},inplace=True)
price['DATE']=pd.to_datetime(price['DATE'])

In [ ]:
df_new=df.merge(price,on=['permno','DATE']).dropna()
df_new['date_cat'].unique()
df_new.to_csv('gkx_merged2.csv')